version: "3.7"
services:
  postgres:
    image: "postgres:13.6-alpine"
    container_name: message_processor
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=message_processor
      - POSTGRES_PASSWORD=message_processor
      - POSTGRES_DB=message_processor
    volumes:
      - ./src/main/resources/db/migration/V1__initial.sql:/docker-entrypoint-initdb.d/init.sql